twig:
    globals:
        image_dir: 'uploads/images/'
        configuration: '@App\Service\ConfigurationService'
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
